"use client";

type Props = {};
export default function Landing({}: Props) {
  return (
    <div className="pt-16">
      <h1>Rich</h1>
      <p className="leading-relaxed">
       Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique quidem molestias consectetur maxime voluptatem ea aut eius, asperiores alias repudiandae nostrum assumenda perferendis, reprehenderit, ullam non accusantium sint. Quia sequi assumenda tempore commodi amet veniam ratione reiciendis non odit saepe aliquam minima aliquid eveniet placeat provident maiores harum incidunt, consequatur, sed accusantium recusandae quos. Magnam at accusantium mollitia eveniet blanditiis nulla eos, illo architecto incidunt natus, repellat atque ab quis aliquid saepe debitis reiciendis, facere sint praesentium cum ipsam aperiam. Perferendis magni suscipit totam eaque voluptatem distinctio molestiae natus deserunt, ipsa pariatur, enim nesciunt dicta. Aliquid aliquam ab numquam repudiandae atque eligendi obcaecati optio delectus sint est, tempora eaque, provident assumenda blanditiis quis aut suscipit tenetur explicabo, beatae fuga voluptatibus quos. Voluptatem quia cum modi temporibus facere, earum dolore et ab? Laborum, id neque voluptates repellendus eos cumque saepe nam. Libero ipsum vitae eius nesciunt voluptates distinctio ex dolor voluptas placeat rerum iusto, ad pariatur, necessitatibus sit eligendi, quos cumque similique. Saepe quae reprehenderit nulla aspernatur laudantium ducimus autem aliquid debitis, accusamus animi explicabo ad, libero nesciunt minima dolorem amet quidem facere itaque architecto similique hic. Saepe optio nihil dignissimos repellat, pariatur assumenda maxime, id, totam tenetur magni officia corporis esse eius modi? Quibusdam, nobis sapiente? Neque aliquam obcaecati sed placeat est delectus quod magni modi quas? Rem maxime, optio reprehenderit nobis quam id exercitationem laborum architecto odio quae esse maiores neque consequatur, corporis vero totam nostrum voluptatem blanditiis amet ad ipsa? Obcaecati ipsam quibusdam harum, dolorem quisquam voluptatem voluptatum atque hic optio magnam unde, ducimus ratione odio sed deserunt? Eveniet laudantium quae modi sint assumenda delectus voluptas hic, consequatur quod tempora est cum? Optio dolor voluptatibus commodi inventore corporis. In accusantium beatae eveniet dicta? Nulla dolor iure, assumenda unde iste laborum tenetur? Id iure voluptas et, dolore itaque modi aut officia nisi voluptatibus odio? Culpa quos, magnam explicabo ex voluptatum quisquam, iusto consequatur praesentium sed rerum nobis nihil unde consectetur nemo magni eveniet maxime. Magnam sequi doloribus illum sit nostrum. Consectetur, saepe ea harum neque rerum fuga molestiae maiores? Tempora, ea quis? Nihil, nemo nostrum ipsum dolore veritatis at!
      </p>
    </div>
  );
}
